-- Skema Database untuk Momo Accessories
-- Copy dan Paste seluruh script ini di SQL Editor Supabase Anda, lalu klik "Run"

-- 1. Buat Tabel Categories
CREATE TABLE categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  icon text
);

-- 2. Buat Tabel Products
CREATE TABLE products (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  price integer NOT NULL,
  stock integer NOT NULL DEFAULT 0,
  description text,
  category text,
  image text
);

-- 3. Buat Tabel Users
CREATE TABLE users (
  id bigint PRIMARY KEY,
  name text,
  email text,
  password text,
  address text
);

-- 4. Buat Tabel Settings (Sebagai Key-Value Store)
CREATE TABLE settings (
  key text PRIMARY KEY,
  value jsonb
);

-- 5. Buat Tabel Carts
CREATE TABLE carts (
  id bigint PRIMARY KEY,
  user_id bigint,
  product_id bigint,
  quantity integer
);

-- 6. Buat Tabel Wishlists
CREATE TABLE wishlists (
  id bigint PRIMARY KEY,
  user_id bigint,
  product_id bigint
);

-- 7. Buat Tabel Orders
CREATE TABLE orders (
  id text PRIMARY KEY,
  user_id bigint,
  date text,
  status text,
  total integer,
  items jsonb
);

-- 8. Buat Tabel Chat History
CREATE TABLE chat_messages (
  id bigint PRIMARY KEY,
  user_id bigint,
  text text,
  sender text,
  time text
);

-- Matikan Row Level Security (RLS) agar frontend bisa langsung akses (Khusus untuk kemudahan saat ini)
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE carts DISABLE ROW LEVEL SECURITY;
ALTER TABLE wishlists DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages DISABLE ROW LEVEL SECURITY;

-- Insert Data Awal Categories
INSERT INTO categories (id, name, icon) VALUES 
  (1, 'Keychain', '🎀'),
  (2, 'Tote Bag', '👜'),
  (3, 'Case HP', '📱'),
  (4, 'Sticker', '✨'),
  (5, 'Boneka', '🧸'),
  (6, 'Gelang', '💎'),
  (7, 'Kalung', '🌷'),
  (8, 'Scrunchie', '🎀')
ON CONFLICT (id) DO NOTHING;

-- Insert Data Awal User
INSERT INTO users (id, name, email, password, address) VALUES 
  (1, 'Dinda Aulia', 'dinda.aulia@gmail.com', 'password123', 'Jl. Mawar No 10')
ON CONFLICT (id) DO NOTHING;

-- Insert Data Awal Produk
INSERT INTO products (id, name, price, stock, description, category, image) VALUES 
  (1, 'Sweet Bunny Keychain', 18000, 25, 'Gantungan kunci akrilik karakter kelinci lucu dengan warna pastel yang menggemaskan. Cocok untuk tas, kunci, atau hadiah!', 'Keychain', 'https://placehold.co/400x400/FFD6E8/333333?text=Bunny+Keychain'),
  (2, 'Cherry Bow Tote Bag', 45000, 10, 'Tote bag kanvas tebal dengan motif pita ceri yang cantik.', 'Tote Bag', 'https://placehold.co/400x400/DCC6FF/333333?text=Cherry+Bow+Tote+Bag'),
  (3, 'Acrylic Bear Keychain', 15000, 30, 'Gantungan kunci beruang pastel yang aesthetic.', 'Keychain', 'https://placehold.co/400x400/FFD6E8/333333?text=Bear+Keychain'),
  (4, 'Daisy Phone Case', 35000, 15, 'Casing handphone motif bunga daisy pelindung ekstra.', 'Case HP', 'https://placehold.co/400x400/DCC6FF/333333?text=Daisy+Phone+Case'),
  (5, 'Pink Scrunchie', 12000, 50, 'Ikat rambut lucu dan super lembut.', 'Scrunchie', 'https://placehold.co/400x400/FFD6E8/333333?text=Pink+Scrunchie'),
  (6, 'Flower Bracelet', 15000, 20, 'Gelang manik-manik bunga pastel.', 'Gelang', 'https://placehold.co/400x400/DCC6FF/333333?text=Flower+Bracelet'),
  (7, 'Bunny Sticker Pack', 10000, 40, 'Koleksi stiker kelinci lucu untuk menghias jurnal.', 'Sticker', 'https://placehold.co/400x400/FFD6E8/333333?text=Bunny+Sticker'),
  (8, 'Heart Charm Bracelet', 18000, 15, 'Gelang manis dengan charm bentuk hati.', 'Gelang', 'https://placehold.co/400x400/DCC6FF/333333?text=Heart+Charm+Bracelet'),
  (9, 'Kawaii Tote Bag', 50000, 25, 'Tote bag desain kawaii untuk sehari-hari.', 'Tote Bag', 'https://placehold.co/400x400/FFD6E8/333333?text=Kawaii+Tote+Bag'),
  (10, 'Purple Heart Case', 38000, 20, 'Casing handphone warna ungu bermotif hati.', 'Case HP', 'https://placehold.co/400x400/DCC6FF/333333?text=Purple+Heart+Case'),
  (11, 'Bunny Mini Doll', 25000, 10, 'Boneka mini kelinci yang imut.', 'Boneka', 'https://placehold.co/400x400/FFD6E8/333333?text=Bunny+Mini+Doll'),
  (12, 'Ribbon Keychain', 12000, 35, 'Gantungan kunci bentuk pita yang cantik.', 'Keychain', 'https://placehold.co/400x400/DCC6FF/333333?text=Ribbon+Keychain')
ON CONFLICT (id) DO NOTHING;

-- Insert Default Settings
INSERT INTO settings (key, value) VALUES 
  ('storeName', '"Momo Accessories"'),
  ('tagline', '"Aksesoris Lucu untuk Hari yang Lebih Berwarna ✨"'),
  ('waNumber', '"6281234567890"'),
  ('email', '"hello@momo.com"'),
  ('instagram', '"momo.acc"'),
  ('tiktok', '"momo.acc"'),
  ('address', '"Jl. Melati No. 123, Jakarta"'),
  ('heroImage', '"https://placehold.co/800x400/FFD6E8/333333?text=Hero+Banner"'),
  ('mascotImage', '"https://placehold.co/400x400/DCC6FF/FFFFFF?text=Rabbit+Bag+Img"'),
  ('promoActive', 'true'),
  ('promoText', '"Diskon 20% untuk semua produk!"')
ON CONFLICT (key) DO NOTHING;

-- Membuat Storage Bucket bernama 'momo-images' dengan Public Access
INSERT INTO storage.buckets (id, name, public) VALUES ('momo-images', 'momo-images', true) ON CONFLICT DO NOTHING;

-- Mengizinkan operasi tanpa batasan (Public access) di bucket momo-images
CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'momo-images');
CREATE POLICY "Public Insert" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'momo-images');
CREATE POLICY "Public Update" ON storage.objects FOR UPDATE TO public USING (bucket_id = 'momo-images');
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE TO public USING (bucket_id = 'momo-images');

-- 10. Aktifkan Realtime Subscription
-- Hapus tabel dari publication jika sudah ada (mencegah error duplikasi), lalu tambahkan
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE categories, products, users, settings, carts, wishlists, orders, chat_messages;
